### PR TITLE
fix incorrect data source name

### PR DESCRIPTION
**Pull request by sheridancbio**
data source was incorrectly given as msk-extract.
The correct data source name is msk-extract-datahub.

### CODE REVIEW

**Comment by ao508** [comment]
@sheridancbio I think the REDCap integration tests may need the updated SSL cert path?

**Comment by ao508** [comment]
@sheridancbio From the Jenkins logs it appears to still be complaining about being able to find the SSL cert path when running the schema integration test for REDCap project `mskimpact_crdb_survey`

**Comment by averyniceday** [comment]
@ao508 @sheridancbio This PR has to be rebased to the front of master. Jenkins builds off the code inside the PR, so if this PR does not have the recent commits adding SSL, it will run the tests w/o SSL.

**Comment by ao508** [comment]
ohh I hadn't realized it didn't have the latest updates from master. thanks @averyniceday

**Comment by sheridancbio** [comment]
Ok .. I will rebase

**Comment by sheridancbio** [comment]
I see .. my mistake. My fork's master branch was not up to date when making the PR. It should be fixed now.

**Pull request merged**
