### PR TITLE
Add Python2 and Python3 requirements files

### PR DESCRIPTION
**Pull request by ao508**
Signed-off-by: Angelica Ochoa <15623749+ao508@users.noreply.github.com>

### CODE REVIEW

**Comment by ao508** [comment]
@averyniceday There might be some modules missing in the python2 requirements file - I tried being comprehensive since I am currently setting up my own environment but I'm sure I missed _something_. 

When you get around to looking at this PR would you mind running the following?

```
python -m pip freeze > py2_requirements.txt
```

and then we can see if anything was missing after all from my environment that you probably already had set up.

**Comment by sheridancbio** [comment]
@ao508 @averyniceday ... I'm just going through old PRs and trying to clean up. I'm not sure if this is helpful @ao508, but I ran these commands on my laptop after checking out your branch of the cmo-pipelines repo (I'm guessing I have some packages installed that are not really needed):
pip --version
pip 19.0.3 from /Library/Python/2.7/site-packages/pip (python 2.7)
pip freeze > py2_requirements.txt
cat py2_requirements.txt 
altgraph==0.10.2
bdist-mpkg==0.5.0
bonjour-py==0.3
certifi==2019.3.9
chardet==3.0.4
future==0.16.0
idna==2.8
macholib==1.5.1
matplotlib==1.3.1
modulegraph==0.10.4
numpy==1.13.1
ordered-set==2.0.2
pandas==0.20.3
py2app==0.7.3
PyLaTeX==1.2.1
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
python-dateutil==1.5
python-Levenshtein==0.12.0
pytz==2013.7
requests==2.21.0
scipy==0.19.1
seaborn==0.8
six==1.4.1
urllib3==1.24.1
xattr==0.6.4

I also did a python3 probe:
python3 -m pip freeze > py3_requirements.txt
cat py3_requirements.txt 
certifi==2020.6.20
chardet==3.0.4
idna==2.10
PyYAML==5.3.1
requests==2.24.0
urllib3==1.25.11

Is this helpful? What can we do to close out this PR?

**Comment by ao508** [comment]
@sheridancbio I'll update this actually, I remember holding off on it because I had a bunch of extra python requirements installed that weren't specific to the project but there's a way to only include the project-specific requirements

**Comment by ao508** [comment]
@sheridancbio this is okay to merge, I'll go ahead and do it myself

**Pull request merged**
